### PR TITLE
Formalized "nitwit" class as "commoner"

### PR DESCRIPTION
**Pull request by noelforte**
_**IMPORTANT:** I'm not a native speaker of any of the other provided languages besides English so if translations were provided by native speakers those translations should be updated by native speakers._

---

Since nitwit is informal language and usually used as an insult when spoken or written, I'd like to submit this pull request as recommendation to formalize the language to something that might not be as polarizing, in this case, I've selected "commoner" but even something as generic as "none" could be used instead; I chose "commoner" as I felt it stays within the vein of village/townsfolk/Dungeons-and-Dragons style characters that this mod appears to capture.

Feel free to edit as you see fit. Thanks for adding this extension to your already awesome mod!!

### CODE REVIEW

**Comment by noelforte** [comment]
Going through my changes, sorry for all the formatting changes! I didn't realize when I was making edits that VS Code was formatting things as I went O_o

**Comment by apace100** [comment]
I was wondering about this. The only reason I chose "Nitwit" as the word, was because it's the word Minecraft uses for villagers who have no profession and don't have the ability to get one. I feel Nitwit feels more in line with Minecraft's world, however being not a native English speaker, I can see how I would miss these negative connotations.

Edit: either way, this PR won't be merged as it is. The formatting changes are a bit disruptive (causing merge conflicts with other translations), and changing the actual origin's ID to `commoner` is a breaking change for existing worlds, it'd have to stay `nitwit` in code.

**Comment by noelforte** [comment]
For sure. Just figured it was worth a conversation. You're free to close this if you'd like.

**Comment by noelforte** [comment]
Closing due to inactivity resolution reached above.

**Pull request closed without merging**
